name: releaser

on:
  push:
    tags:
        - v*.*.*

permissions:
  contents: write
  packages: write
concurrency:
  group: release
  cancel-in-progress: true

jobs:
  tag:
    uses: kdwils/homelab-workflow/.github/workflows/update-image-tag.yml@main
    secrets: inherit
    with:
      image: kdwils/constellation
      registry: ghcr.io

  charts:
    needs: [tag]
    uses: kdwils/homelab-workflow/.github/workflows/helm-release.yml@main